project_name: "Pokedex"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done"]
labels: ["dev", "bug", "feature", "ux", "os", "device", "pokedex", "ribombee"]
milestones: []
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "vim"
auto_open_browser: true
default_port: 6420
remote_operations: true
auto_commit: false
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 30
